---
# get the list of existing dservers and add the missing ones

- name: get list of current distributedSearch servers
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - dserver
  # Same command is in search_head/tasks/search_peers.yml
  shell: sed -n '/^\[distributedSearch\]$/,+1p' {{ splunk_home }}/etc/system/local/distsearch.conf | grep servers | awk -F= '{print $2}' | sed -e 's%https\://%%g' -e 's/\:[0-9]*//g' | tr -d " "
  become: yes
  become_user: "{{ splunk_user }}"
  check_mode: no
  register: current_dservers
  args:
    warn: false

- name: call add_dserver
  tags:
    - splunk
    - splunk_baseconfig
    - monitoring_console
    - dserver
  include_tasks: add_dserver.yml
  with_items:
    - "{{ splunk_dservers | difference(current_dservers.stdout.split(',')|list) }}"
  loop_control:
    loop_var: dserver_name
  when: "splunk_dservers|difference(current_dservers.stdout.split(',')|list)|length > 0"
