---
# This playbook install a hosts file for all the hosts

- name: add splunk hosts to /etc/hosts
  tags:
    - common
    - hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ splunk_hosts_entries }}
    marker: "# {mark} SPLUNKENIZER MANAGED BLOCK (splunk hosts)"
  become: yes
  become_user: root
