---
# Main playbook for this role

- name:
  import_tasks: set_hostname.yml
  when: ansible_os_family|lower != 'windows'

- name:
  import_tasks: packages.yml
  when: ansible_os_family|lower != 'windows'

- name:
  import_tasks: users.yml
  when: ansible_os_family|lower != 'windows'

- name:
  import_tasks: time.yml
  when: ansible_os_family|lower != 'windows'

- name:
  import_tasks: disable_selinux.yml
  when:
    - disable_selinux|default(false) == true
    - ansible_os_family|lower != 'windows'
    - "'role_universal_forwarder' not in group_names"

- name:
  import_tasks: fix_time_sync.yml
  when:
    - ansible_os_family|lower != 'windows'
    - enable_time_sync_cron|default(false) == true
