---
# This playbook install the base config app

- name: Fail if homePath != coldPath (SmartStore)
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  fail:
    msg: "homePath ({{splunk_volume_defaults.homePath|default('primary')}}) must be equal to coldPath ({{splunk_volume_defaults.coldPath|default('primary')}}) when using SmartStore"
  when: 
    - splunk_volume_defaults.remotePath is defined
    - splunk_volume_defaults.homePath|default("primary") != splunk_volume_defaults.coldPath|default("primary")

- name: "({{ app_name }}) configure some indexes"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  blockinfile:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    insertafter: "# CUSTOMER INDEXES"
    marker: "# {mark} ANSIBLE MANAGED BLOCK Index: {{ item }}"
    content: |
      [{{ item }}]
      homePath   = volume:{{splunk_volume_defaults.homePath|default("primary")}}/{{ item }}/db
      coldPath   = volume:{{splunk_volume_defaults.coldPath|default("primary")}}/{{ item }}/colddb
      thawedPath = $SPLUNK_DB/{{ item }}/thaweddb
  with_items: "{{ splunk_indexes | default('test') }}"
  notify: restart splunk

- name: "({{ app_name }}) configure volume for homePath"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  replace:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    regexp: '^(homePath\s*=\s*)volume:\w*'
    replace: '\1volume:{{splunk_volume_defaults.homePath|default("primary")}}'
  notify: restart splunk

- name: "({{ app_name }}) configure volume for coldPath"
  tags:
    - splunk
    - splunk_baseconfig
    - org_all_indexes
  replace:
    path: "{{ app_path }}/{{ app_dest_name }}/local/indexes.conf"
    regexp: '^(coldPath\s*=\s*)volume:\w*'
    replace: '\1volume:{{splunk_volume_defaults.coldPath|default("primary")}}'
  notify: restart splunk
