---
# This playbook install the apps required in a server

- name: get list of current distributedSearch peers (single indexers)
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - search_peer
  # Same command is in monitoring_console/tasks/dserver.yml
  shell: sed -n '/^\[distributedSearch\]$/,+1p' {{ splunk_home }}/etc/system/local/distsearch.conf | grep servers | awk -F= '{print $2}' | sed -e 's%https\://%%g' -e 's/\:[0-9]*//g' | tr -d " "
  become: yes
  become_user: "{{ splunk_user }}"
  check_mode: no
  changed_when: false
  register: current_dservers
  args:
    warn: false

- name: adding new distributedSearch peer (single indexers)
  tags:
    - splunk
    - splunk_baseconfig
    - search_head
    - search_peer
  command: "{{ splunk_home }}/bin/splunk add search-server {{ item }}:8089 -remoteUsername admin -remotePassword {{splunk_admin_password}} -auth admin:{{splunk_admin_password}}"
  with_items:
    - "{{ splunk_search_peer_idx_list | difference(current_dservers.stdout.split(',')|list) }}"
  become: yes
  become_user: "{{ splunk_user }}"
  when: "splunk_search_peer_idx_list|difference(current_dservers.stdout.split(',')|list)|length > 0"
