---
# add a splunk license if not existing

- name: add splunk hosts to /etc/hosts
  hosts: all
  become: yes
  become_user: root

  tasks:

    - name: call hosts from role common
      include_role:
        name: common
        tasks_from: hosts
